config/routes.rb
Bois::Application.routes.draw do

  
	match '' => 'top#index', :via => [:get], :as => :top_index
	match 'top' => 'top#index', :via => [:get]
	match 't:id' => 'top#topic', :via => [:get], :as => :top_topic

	match 'request' => 'request#index', :via => [:get,:post], :as => :request_index

	match 'power' => 'power#index', :via => [:get], :as => :power_index
	match 'power/list' => 'power#list', :via => [:post], :as => :power_list
	match 'power/graph' => 'power#graph', :via => [:get,:post], :as => :power_graph

	match 'children' => 'children#index', :via => [:get], :as => :children_index
	match 'children/list' => 'children#list', :via => [:post], :as => :children_list
	match 'children/form' => 'children#form', :via => [:post], :as => :children_form
	match 'children/create' => 'children#create', :via => [:post], :as => :children_create
	match 'children/edit' => 'children#edit', :via => [:post], :as => :children_edit
	match 'children/delete' => 'children#delete', :via => [:post], :as => :children_delete
	match 'children/passwd' => 'children#passwd', :via => [:post], :as => :children_passwd

end

app/controllers/top_controller.rb
# encoding: utf-8
class TopController < ApplicationBaseController

=begin
	before_filter :only => [:index] do |controller|
		controller.beforePageFilter(Codes::FUNCTION_CODE_USERS)
	end
	before_filter :beforeAjaxFilter, :except => [:index]
=end

	# メイン画面
	def index
		
		@results=[]
		for i in 1..10
			@results << {:title=>'7/15　第1サイト　3Fにて空調フィルター交換作業がございます', :category=>'メンテナンス', :id=>1}
			@results << {:title=>'6/28 17:30　東京電力サービス内にて停電が発生しました', :category=>'障害', :id=>2}
			@results << {:title=>'省エネにご協力ください', :category=>'お知らせ', :id=>3}
		end
		
		
		respond_to do |format|
			format.html
		end
	end

	# 詳細画面
	def topic
		
		
		respond_to do |format|
			format.html
		end
	end

end

app/views/top/index.html.erb
<% content_for :title do %>トップ<% end %>

<% content_for :script do %>

<%
=begin
%>

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// タグを含むHTMLを定義する場合は<script>～</scirpt>の中で変数定義すること
// IE8のevalに不具合があり、コンパイルエラーになってしまうため。
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// evalで実行する箇所のコメントはブロックコメントを使用すること
// IE8のevalに不具合があり、コンパイルエラーになってしまうため。
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
<%
=end
%>


<% "// #defined html" %>
var searchForm = '';
<%
=begin
%>
searchForm += '<form name="userserch_form" id="userserch_form">';
searchForm += '<table cellspacing="0" cellpadding="0" border="0" class="search_table">';
searchForm += '<tr>';
searchForm += '<th>ログインID</th><td><input type="text" name="s_login_id" class="width150"></td>';
searchForm += '</tr>';
searchForm += '<tr>';
searchForm += '<th>お名前</th><td><input type="text" name="s_name" class="width150"></td>';
searchForm += '</tr>';
searchForm += '<tr>';
searchForm += '<th>電話</th><td><input type="text" name="s_tel" class="width150"></td>';
searchForm += '</tr>';

searchForm += '<tr>';
searchForm += '<th>メールアドレス</th><td><input type="text" name="s_email" class="width150"></td>';
searchForm += '</tr>';


searchForm += '<th>権限</th><td>'
<% for role in @roles %>
searchForm += '<div style="clear:both"><label><input type="checkbox" name="s_role" value="<%= role.id %>"><%= role.role_name %></label></div>'
<% end %>
searchForm += '</td>'
searchForm += '</tr>';

searchForm += '<tr>';
searchForm += '<th>状態</th><td><label><input type="checkbox" name="s_invalid_flg" value="1" id="s_invalid_flg">無効ユーザーを含める</label></td>';
searchForm += '</tr>';

searchForm += '</table>';
searchForm += '<div class="control">';
searchForm += '<input type="button" id="usersearch_button" value="検索" onclick="showSearchWindow();">';
searchForm += '<input type="button" id="close_button" value="閉じる" onclick="rainy3.hideSubmenu();">';
searchForm += '</div>';
searchForm += '</form>';

var form1 = '<input type="hidden" name="id" value=""><input type="hidden" name="notice" value="false" id="form_user_notice"><input type="text" name="login_id" value="" class="width100" maxlength="<%= Ante::Application.config.user_login_id_max %>">';
var form2 = '<input type="text" name="last_name" value="" class="width75" maxlength="<%= Ante::Application.config.user_last_name_max %>">　<input type="text" name="first_name" value="" class="width75" maxlength="<%= Ante::Application.config.user_first_name_max %>">';
var form3 = '<input type="text" name="tel" value="" class="width200" maxlength="<%= Ante::Application.config.common_tel_max %>">';
var form4 = '<input type="text" name="email" value="" class="width200" maxlength="<%= Ante::Application.config.common_email_max %>">';
var form5 = '<select name="role_id">'
		form5 += '<option value="">お選びください</option>'
		<% for role in @roles %>
		form5 += '<option value="<%= role.id %>"><%= role.role_name %></option>'
		<% end %>
		form5 += '</select>'
var form6 = '<input type="password" name="password" value="" class="width100" maxlength="<%= Ante::Application.config.user_password_max %>">';
var form7 = '<input type="text" name="last_name_kana" value="" class="width75" maxlength="<%= Ante::Application.config.user_last_name_kana_max %>">　<input type="text" name="first_name_kana" value="" class="width75" maxlength="<%= Ante::Application.config.user_first_name_kana_max %>">';


var form7 = '<input type="text" name="last_name_kana" value="" class="width75" maxlength="<%= Ante::Application.config.user_last_name_kana_max %>">　<input type="text" name="first_name_kana" value="" class="width75" maxlength="<%= Ante::Application.config.user_first_name_kana_max %>">';

var form8 = '';
		form8 += '<label><input type="radio" name="invalid_flg" value="false" checked>有効</label>';
		form8+= '<label><input type="radio" name="invalid_flg" value="true">無効</label>';
		form8 += '';
<%
=end
%>

<% "// #defined function" %>
function showSearchWindow(){
	rainy3.getWindow('content2_1').setCondition(app.formParam2jsonData('userserch_form'), false);
	rainy3.getWindow('content2_1').load();
	rainy3.hideSubmenu();
}
<% end %>


<div class="overlay_base_position">
<%= render 'common/pre_load_image' %>

<div id="display_protection"></div>
<img src="img/loading.gif" id="display_loading"/>
<div id="x_contents_resize_border"></div>
<div id="y_contents_resize_border"></div>
<div id="message_window"><div class="lt frame"></div><div class="ll frame"></div><div class="lb frame"></div><div class="tt frame"></div><div class="bb frame"></div><div class="rt frame"></div><div class="rr frame"></div><div class="rb frame"></div><div class="title"></div><div class="message"></div><div class="control"><input type="button" value="OK" class="control_ok" id="message_window_ok"><input type="button" value="CANCEL" class="control_cancel" id="message_window_cancel"></div></div>
<div id="submenu" class="submenu"><div class="lt frame"></div><div class="ll frame"></div><div class="lb frame"></div><div class="tt frame"></div><div class="bb frame"></div><div class="rt frame"></div><div class="rr frame"></div><div class="rb frame"></div><div class="contents"></div></div>
<div><% "// .display_protection" %>
<div id="header" class="frame_width">
<% "// overlayで背後にfocusが回らないようにする入力エリア" %>
<div class="tab_stop_box"><input type="text" name="tab_stop_1" class="tab_stop"></div>


<div class="base_head">
<div style="width:970px;margin-left:auto;margin-right:auto;" class="">
<a href="<%= top_index_path %>"><img src="img/logo.png" class="logo"></a>

<%= render 'common/login_info' %>
</div>

</div>
<div  class="global_menu">

<div class="menu_frame" style="width:615px;">
<img src="/img/bois/global_menu_delim.png">
<a href="javascript:void(0);" onclick="openPowerWindow();return false;"><div><img src="/img/bois/global_menu_1.png"></div></a>
<img src="/img/bois/global_menu_delim.png">
<a href="<%= request_index_path %>"><div><img src="/img/bois/global_menu_2.png"></div></a>
<img src="/img/bois/global_menu_delim.png">
<a href="<%= children_index_path %>"><div><img src="/img/bois/global_menu_3.png"></div></a>
<img src="/img/bois/global_menu_delim.png">
<a href="/"><div><img src="/img/bois/global_menu_4.png"></div></a>
<img src="/img/bois/global_menu_delim.png">
	

</div>
	
	
	
</div>

<%
=begin
%>
<%= render 'common/login_info' %>
<%
=end
%>

</div><% "// #header" %>
<div class="contents_y_space"></div>
<div id="contents">

<% "// コンテンツの折り返しを抑止するために、左右20pxずつのマージンを確保する" %>
<% "// 左margine:20px, 幅：.frame_width-40px;" %>

<div id="left_margin" class="x_content" style="width:5px;position:fixed;">
<div id="left_margin_height" class="y_content" style="height:10px;">

</div><%  "#left_margin_height" %>
</div><%  "#left_margin" %>



<div id="main" class="x_content" style="width:960px;position:fixed;">
<div id="main_topics" class="y_content" style="height:4px;position:fixed;">
<div id="main_topics_body" class="r3base">



<div class="r3control_header">
var header = {
  title:"トピックス",
  title_width:"150",
  controls:[]
}
</div>

<ul class="topics">

<% for result in @results %>

<li><a href="<%= top_topic_path(result[:id]) %>">【<%= result[:category] %>】<%= result[:title] %></a></li>

<% end %>
</ul>
</div><% "// #main_topics_body" %>
</div><% "// #main_topics" %>

<div id="main_menu" class="y_content" style="height:6px;">
<div id="main_menu_body" class="r3base">

<div class="r3control_header">
var header = {
  title:"ご利用メニュー",
  title_width:"150",
  controls:[]
}
</div>

<div class="top_menu top_menu_left"><a href="/"><img src="/img/bois/top_menu_1.png"></a></div>
<div class="top_menu top_menu_right"><a href="/"><img src="/img/bois/top_menu_2.png"></a></div>
<div class="top_menu top_menu_left"><a href="/"><img src="/img/bois/top_menu_3.png"></a></div>
<div class="top_menu top_menu_right"><a href="/"><img src="/img/bois/top_menu_4.png"></a></div>

</div><% "// #main_menu_body" %>
</div><%  "// #main_menu" %>
</div><%  "// #main" %>

<div id="right_margin" class="x_content" style="width:5px;position:fixed;">
<div id="right_margin_height" class="y_content" style="height:10px;">

</div><%  "#right_margin_height" %>
</div><%  "#right_margin" %>

</div><% "// #contents" %>
<div class="contents_y_space"></div>
<div id="footer" class="frame_width">

<% "// overlayで背後にfocusが回らないようにする入力エリア" %>
<div class="tab_stop_box"><input type="text" name="tab_stop_2" class="tab_stop"></div>

</div><% "// #footer" %>

app/views/top/topic.html.erb
<% content_for :title do %>トップ<% end %>

<% content_for :script do %>

<%
=begin
%>

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// タグを含むHTMLを定義する場合は<script>～</scirpt>の中で変数定義すること
// IE8のevalに不具合があり、コンパイルエラーになってしまうため。
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// evalで実行する箇所のコメントはブロックコメントを使用すること
// IE8のevalに不具合があり、コンパイルエラーになってしまうため。
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
<%
=end
%>

<% "// #defined html" %>

<% "// #defined function" %>

<% end %>


<div class="overlay_base_position">
<%= render 'common/pre_load_image' %>

<div id="display_protection"></div>
<img src="img/loading.gif" id="display_loading"/>
<div id="x_contents_resize_border"></div>
<div id="y_contents_resize_border"></div>
<div id="message_window"><div class="lt frame"></div><div class="ll frame"></div><div class="lb frame"></div><div class="tt frame"></div><div class="bb frame"></div><div class="rt frame"></div><div class="rr frame"></div><div class="rb frame"></div><div class="title"></div><div class="message"></div><div class="control"><input type="button" value="OK" class="control_ok" id="message_window_ok"><input type="button" value="CANCEL" class="control_cancel" id="message_window_cancel"></div></div>
<div id="submenu" class="submenu"><div class="lt frame"></div><div class="ll frame"></div><div class="lb frame"></div><div class="tt frame"></div><div class="bb frame"></div><div class="rt frame"></div><div class="rr frame"></div><div class="rb frame"></div><div class="contents"></div></div>
<div><% "// .display_protection" %>
<div id="header" class="frame_width">
<% "// overlayで背後にfocusが回らないようにする入力エリア" %>
<div class="tab_stop_box"><input type="text" name="tab_stop_1" class="tab_stop"></div>


<div class="base_head">
<div style="width:970px;margin-left:auto;margin-right:auto;" class="">
<a href="<%= top_index_path %>"><img src="img/logo.png" class="logo"></a>

<%= render 'common/login_info' %>
</div>

</div>
<div  class="global_menu">

<div class="menu_frame" style="width:615px;">
<img src="/img/bois/global_menu_delim.png">
<a href="javascript:void(0);" onclick="openPowerWindow();return false;"><div><img src="/img/bois/global_menu_1.png"></div></a>
<img src="/img/bois/global_menu_delim.png">
<a href="<%= request_index_path %>"><div><img src="/img/bois/global_menu_2.png"></div></a>
<img src="/img/bois/global_menu_delim.png">
<a href="<%= children_index_path %>"><div><img src="/img/bois/global_menu_3.png"></div></a>
<img src="/img/bois/global_menu_delim.png">
<a href="/"><div><img src="/img/bois/global_menu_4.png"></div></a>
<img src="/img/bois/global_menu_delim.png">
	

</div>
	
	
	
</div>

<%
=begin
%>
<%= render 'common/login_info' %>
<%
=end
%>

</div><% "// #header" %>
<div class="contents_y_space"></div>
<div id="contents">

<% "// コンテンツの折り返しを抑止するために、左右20pxずつのマージンを確保する" %>
<% "// 左margine:20px, 幅：.frame_width-40px;" %>

<div id="left_margin" class="x_content" style="width:5px;position:fixed;">
<div id="left_margin_height" class="y_content" style="height:10px;">

</div><%  "#left_margin_height" %>
</div><%  "#left_margin" %>



<div id="main" class="x_content" style="width:960px;position:fixed;">
<div id="main_topics" class="y_content" style="height:4px;position:fixed;">
<div id="main_topics_body" class="r3base">



<div class="r3control_header">
var header = {
  title:"省エネにご協力下さい ［お知らせ］",
  title_width:"500",
  controls:[]
}
</div>

<div class="topic_detail">
東日本大地震以降、電力各社での総発電量の低下に伴い、サイトご利用者様にも節電のご協力をお願い致しております。<br />
第1サイト　B1Fでは、ご利用になるお客様がコロケーション内照明の点灯をお願い致します。<br />
※消灯は弊社NOCが対応致します<br />
</div>
<div class="topic_link">
<a href="<%= top_index_path %>">
＜一覧に戻る＞
</a>
</div>


</div><% "// #main_topics_body" %>
</div><% "// #main_topics" %>

</div><%  "// #main" %>

<div id="right_margin" class="x_content" style="width:5px;position:fixed;">
<div id="right_margin_height" class="y_content" style="height:10px;">

</div><%  "#right_margin_height" %>
</div><%  "#right_margin" %>

</div><% "// #contents" %>
<div class="contents_y_space"></div>
<div id="footer" class="frame_width">

<% "// overlayで背後にfocusが回らないようにする入力エリア" %>
<div class="tab_stop_box"><input type="text" name="tab_stop_2" class="tab_stop"></div>

</div><% "// #footer" %>