config/routes.rb
Bois::Application.routes.draw do

  
	match '' => 'top#index', :via => [:get], :as => :top_index
	match 'top' => 'top#index', :via => [:get]
	match 't:id' => 'top#topic', :via => [:get], :as => :top_topic

	match 'request' => 'request#index', :via => [:get,:post], :as => :request_index

	match 'power' => 'power#index', :via => [:get], :as => :power_index
	match 'power/list' => 'power#list', :via => [:post], :as => :power_list
	match 'power/graph' => 'power#graph', :via => [:get,:post], :as => :power_graph

	match 'children' => 'children#index', :via => [:get], :as => :children_index
	match 'children/list' => 'children#list', :via => [:post], :as => :children_list
	match 'children/form' => 'children#form', :via => [:post], :as => :children_form
	match 'children/create' => 'children#create', :via => [:post], :as => :children_create
	match 'children/edit' => 'children#edit', :via => [:post], :as => :children_edit
	match 'children/delete' => 'children#delete', :via => [:post], :as => :children_delete
	match 'children/passwd' => 'children#passwd', :via => [:post], :as => :children_passwd

end

app/controllers/children_controller.rb
# encoding: utf-8
class ChildrenController < ApplicationBaseController

=begin
	before_filter :only => [:index] do |controller|
		controller.beforePageFilter(Codes::FUNCTION_CODE_USERS)
	end
	before_filter :beforeAjaxFilter, :except => [:index]
=end

	# メイン画面
	def index
		# 権限の取得
		respond_to do |format|
			format.html # index.html.erb
		end
	end

	# 一覧
	def list
		@result = Codes::RAINY3_RESULT_CODE_OK.value
		@title = ''
		@message = ''
		@page={:page=>params[:page], :page_size=>0, :total=>0, :results=>[]}
		
		begin
#			@page = User.getPageList(params)
		rescue => ex
			Rails.logger.error(ex.backtrace.join(", "))
			@result = Codes::RAINY3_RESULT_CODE_ABEND.value
			@title=Messages::FORM_READ_ERROR_TITLE.get
			@message = Messages::FORM_READ_ERROR_COMMON_MESSAGE.get
		ensure
			respond_to do |format|
				format.xml { render :layout => false }
			end
		end
	end

	# 一覧
	def list
		@result = Codes::RAINY3_RESULT_CODE_OK.value
		@title = ''
		@message = ''
		@page={:page=>params[:page], :page_size=>0, :total=>0, :results=>[]}

		begin

			@dummy = []

			@dummy << 1
			@dummy << 2
			@dummy << 3
			@dummy << 4
			@dummy << 5
			@dummy << 6
			@dummy << 7
			@dummy << 8
			@dummy << 9
			@dummy << 10

		rescue => ex
			Rails.logger.error(ex.backtrace.join(", "))
			@result = Codes::RAINY3_RESULT_CODE_ABEND.value
			@title=Messages::FORM_READ_ERROR_TITLE.get
			@message = Messages::FORM_READ_ERROR_COMMON_MESSAGE.get
		ensure
			respond_to do |format|
				format.xml { render :layout => false }
			end
		end
	end

	# フォーム
	def form

		@result = Codes::RAINY3_RESULT_CODE_OK.value
		@title=''
		@message = ''
		@focus = 'customer_name'
		@validators = Validators.new
		@record = nil

		begin
=begin
			@record = Estimate.getRecord(params[:id].to_i)
			
			if @record == nil
				raise NilRecordException
			end
			# 請求数を取得
			@paymentCount = Payment.where(:del_flg=>false, :estimate_id=>params[:id].to_i).count
			# 関連請求を取得
			@relations = Payment.getRelationalPayments(@record[:id], nil)
=end
		rescue NilRecordException => e1
			@result = Codes::RAINY3_RESULT_CODE_ABEND.value
			@title=Messages::FORM_READ_ERROR_TITLE.get
			@message = Messages::FORM_READ_ERROR_COMMON_MESSAGE.get
		rescue => ex
			Rails.logger.error(ex)
			Rails.logger.error(ex.backtrace.join(", "))
			@result = Codes::RAINY3_RESULT_CODE_ABEND.value
			@title=Messages::FORM_READ_ERROR_TITLE.get
			@message = Messages::FORM_READ_ERROR_COMMON_MESSAGE.get
		ensure
			respond_to do |format|
				format.xml { render :layout => false }
			end
		end
	end


	# 新規登録
	def create

		@result = Codes::RAINY3_RESULT_CODE_OK.value
		@title=''
		@message = ''
		@validators = Validators.new
		@record = nil

		begin
		# 入力値の整形
			ActionUtils.trimParams(params)

=begin
			# 入力チェック（Error:IllegalParamsException）
			@validators.validateUser(params, :create)

			# レコードの生成
			# パスワードをSHA256に変換
			@record = User.create!(
											:last_name=>params[:last_name][0],
											:first_name=>params[:first_name][0],
											:last_name_kana=>params[:last_name_kana][0],
											:first_name_kana=>params[:first_name_kana][0],
											:login_id=>params[:login_id][0],
											:password=>PasswordUtils.toHash(params[:password][0]),
											:role_id=>params[:role_id][0].to_i,
											:tel=>params[:tel][0],
											:email=>params[:email][0],
											:del_flg=>false,
											:invalid_flg=>params[:invalid_flg][0]
										)

			# 成功時メール通知が必要な場合
			if params[:notice][0] == 'true'
				# メールを送信する（Error:MailTransferException）
				MailUtils.deliver(
						SystemMailer.createUserNotify(
																	params[:email][0],
																	params[:last_name][0] + " " + params[:first_name][0], 
																	params[:login_id][0], 
																	params[:password][0]
																	))
			end
=end
		rescue IllegalParamsException => e1
			@result = Codes::RAINY3_RESULT_CODE_USER_ERROR.value
		rescue => ex
			Rails.logger.error(ex)
			Rails.logger.error(ex.backtrace.join(", "))
			# 登録失敗時、画面にエラーを表示し、再入力を促す
			@result = Codes::RAINY3_RESULT_CODE_ABEND.value
			@title=Messages::FORM_CREATE_ERROR_TITLE.get
			@message = Messages::FORM_CREATE_ERROR_COMMON_MESSAGE.get
		ensure
			respond_to do |format|
				format.xml { render :layout => false, :template => 'children/form'} # form.html.erb
			end

		end

	end

end

app/views/children/form.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<rainy3 type="response">
<head>
<result><%= @result %></result>
<title><%= @title %></title>
<message><%= @message %></message>
<forward></forward>
<data_type>form</data_type>
</head>

<body>
<focus><%= r3focus(@validators) %></focus>

<messages>
<%= r3errors(@validators)%>
</messages>

<fields>


<field id="id">
<values>
<value>1</value>
</values>
</field>

<field id="bois_id">
<values>
<value>bbt</value>
</values>
</field>

<field id="user_name">
<values>
<value>株式会社BBT</value>
</values>
</field>

<field id="person_name">
<values>
<value>山田 太郎</value>
</values>
</field>

<field id="mail">
<values>
<value>bbt@bbtower.co.jp</value>
</values>
</field>

<field id="tel">
<values>
<value>090-1111-2222</value>
</values>
</field>

<field id="role">
<values>
<value>1</value>
</values>
</field>

<field id="status">
<values>
<value>true</value>
</values>
</field>

</fields>

</body>

</rainy3>

app/views/children/index.html.erb
<% content_for :title do %>子アカウント管理<% end %>

<% content_for :head do %>
<script type="text/javascript" src="js/rainy3.bois.child.form.js" charset="utf-8"></script>
<% end %>
	
<% content_for :script do %>

<%
=begin
%>

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// タグを含むHTMLを定義する場合は<script>～</scirpt>の中で変数定義すること
// IE8のevalに不具合があり、コンパイルエラーになってしまうため。
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// evalで実行する箇所のコメントはブロックコメントを使用すること
// IE8のevalに不具合があり、コンパイルエラーになってしまうため。
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
<%
=end
%>


<% "// #defined html" %>
var searchForm = '';
searchForm += '<form name="form1" id="form1">';
searchForm += '<table cellspacing="0" cellpadding="0" border="0" class="search_table">';
searchForm += '<tr>';
searchForm += '<th>親アカウント</th><td>';

searchForm += '<select name="parent_account">';
searchForm += '<option value="">▽</option>';
searchForm += '<option value="1">BBT</option>';
searchForm += '<option value="2">BBT2</option>';
searchForm += '<option value="3">BB3</option>';

searchForm += '</select>';


searchForm += '</td>';
searchForm += '</tr>';
searchForm += '</table>';
searchForm += '<div class="control">';
searchForm += '<input type="button" id="button1" value="検索" onclick="seachChildren();">';
searchForm += '<input type="button" id="button2" value="閉じる" onclick="rainy3.hideSubmenu();">';
searchForm += '</div>';
searchForm += '</form>';


var searchForm2 = '';
searchForm2 += '<form name="form1" id="form1">';
searchForm2 += '<table cellspacing="0" cellpadding="0" border="0" class="search_table">';
searchForm2 += '<tr>';
searchForm2 += '<th width="100">第一サイト</th><td>';
searchForm2 += '<label><input type="checkbox" name="a" value="1" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="2" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="3" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="4" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="5" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="6" id="s_invalid_flg">3F</label>';
searchForm2 += '</td>';
searchForm2 += '</tr>';
searchForm2 += '<tr>';
searchForm2 += '<th>第二サイト</th><td>';
searchForm2 += '<label><input type="checkbox" name="a" value="1" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="2" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="3" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="4" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="5" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="6" id="s_invalid_flg">3F</label>';
searchForm2 += '</td>';
searchForm2 += '</tr>';
searchForm2 += '<tr>';
searchForm2 += '<th>第二サイト</th><td>';
searchForm2 += '<label><input type="checkbox" name="a" value="1" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="2" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="3" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="4" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="5" id="s_invalid_flg">3F</label>';
searchForm2 += '<label><input type="checkbox" name="a" value="6" id="s_invalid_flg">3F</label>';
searchForm2 += '</td>';
searchForm2 += '</tr>';
searchForm2 += '</table>';
searchForm2 += '<div class="control">';
searchForm2 += '<input type="button" id="button3" value="絞込" onclick="">';
searchForm2 += '<input type="button" id="button4" value="閉じる" onclick="rainy3.hideSubmenu();">';
searchForm2 += '</div>';
searchForm2 += '</form>';


var form1 = '<input type="hidden" name="id" value="">';
		form1 += '<input type="text" name="bois_id" value="" class="width150">';

var form2 = '<input type="password" name="password" value="" class="width150">';
var form3 = '<input type="text" name="user_name" value="" class="width150">';
var form4 = '<input type="text" name="person_name" value="" class="width150">';
var form5 = '<input type="text" name="mail" value="" class="width150">';
var form6 = '<input type="text" name="tel" value="" class="width150">';
var form7 = '<select name="role">';
		form7 += '<option value="">▽</option>';
		form7 += '<option value="1">親</option>';
		form7 += '<option value="2">子</option>';
		form7 += '</select>';
var form8 = '<label><input type="radio" name="status" value="false" checked>有効</label>';
		form8 += '<label><input type="radio" name="status" value="true">無効</label>';
var form9 = '<textarea name="note" rows="10" style="width:250px"></textarea>';


<% "// #defined function" %>
function showSearchWindow(){
	rainy3.getWindow('content2_1').setCondition(app.formParam2jsonData('userserch_form'), false);
	rainy3.getWindow('content2_1').load();
	rainy3.hideSubmenu();
}
function createUser(){
	rainy3.getWindow('main_form').send('<%= children_create_path %>', function(){rainy3.getWindow('main_list').reload();})
}
function seachChildren(){
	rainy3.getWindow('main_list').setCondition(app.formParam2jsonData('form1'), false);
	rainy3.getWindow('main_list').load();
	rainy3.hideSubmenu();
}
<% end %>


<div class="overlay_base_position">
<%= render 'common/pre_load_image' %>

<div id="display_protection"></div>
<img src="img/loading.gif" id="display_loading"/>
<div id="x_contents_resize_border"></div>
<div id="y_contents_resize_border"></div>
<div id="message_window"><div class="lt frame"></div><div class="ll frame"></div><div class="lb frame"></div><div class="tt frame"></div><div class="bb frame"></div><div class="rt frame"></div><div class="rr frame"></div><div class="rb frame"></div><div class="title"></div><div class="message"></div><div class="control"><input type="button" value="OK" class="control_ok" id="message_window_ok"><input type="button" value="CANCEL" class="control_cancel" id="message_window_cancel"></div></div>
<div id="submenu" class="submenu"><div class="lt frame"></div><div class="ll frame"></div><div class="lb frame"></div><div class="tt frame"></div><div class="bb frame"></div><div class="rt frame"></div><div class="rr frame"></div><div class="rb frame"></div><div class="contents"></div></div>
<div><% "// .display_protection" %>
<div id="header" class="frame_width">
<% "// overlayで背後にfocusが回らないようにする入力エリア" %>
<div class="tab_stop_box"><input type="text" name="tab_stop_1" class="tab_stop"></div>


<div class="base_head">
<div style="width:970px;margin-left:auto;margin-right:auto;" class="">
<a href="<%= top_index_path %>"><img src="img/logo.png" class="logo"></a>
</div>
</div>
<div  class="global_menu">

<div class="menu_frame" style="width:615px;">
<img src="/img/bois/global_menu_delim.png">
<a href="javascript:void(0);" onclick="openPowerWindow();return false;"><div><img src="/img/bois/global_menu_1.png"></div></a>
<img src="/img/bois/global_menu_delim.png">
<a href="<%= request_index_path %>"><div><img src="/img/bois/global_menu_2.png"></div></a>
<img src="/img/bois/global_menu_delim.png">
<a href="<%= children_index_path %>" class="selected"><div><img src="/img/bois/global_menu_3.png"></div></a>
<img src="/img/bois/global_menu_delim.png">
<a href="/"><div><img src="/img/bois/global_menu_4.png"></div></a>
<img src="/img/bois/global_menu_delim.png">
	
</div>
</div>

</div><% "// #header" %>
<div class="contents_y_space"></div>
<div id="contents">

<% "// コンテンツの折り返しを抑止するために、左右20pxずつのマージンを確保する" %>
<% "// 左margine:20px, 幅：.frame_width-40px;" %>

<div id="left_margin" class="x_content" style="width:5px;position:fixed;">
<div id="left_margin_height" class="y_content" style="height:10px;">

</div><%  "#left_margin_height" %>
</div><%  "#left_margin" %>


<div id="main" class="x_content" style="width:960px;">
<div id="main_list" class="y_content" style="height:3px;">
<div id="main_list_body" class="r3grid">
<div class="r3control_header">

var search=new Rainy3Submenu(300, 100, searchForm);
search.setPreLoadAction(function(){
	rainy3.setButtonAction('button1');
	rainy3.setButtonAction('button2');
	app.jsonData2formParam(rainy3.getWindow('main_list').getCondition(), 'form1');
});
search.setLoadAction(function(){
});
var header = {
  title:"子アカウント一覧",
  title_width:"150",
  controls:[
  		{id:'search', label:'親アカウント選択', icon:'img/small_icon/search.png', disabledicon:'img/small_icon/search_disabled.png', click:null, submenu:search, initdisable:false},
  ]
}
</div>
var grid = 
{
	url:'<%= children_list_path %>',
	select:'single',
	initload:true,
	initsort:'customer_name',
	initdirection:'asc',
	loadaction:function(){},
	selectaction:function(id){
		rainy3.getWindow('main_form').setCondition({id:id});
		rainy3.getWindow('main_form').load();
	},
	deselectaction:function(id){
		rainy3.getWindow('main_form').reset();
	},
	props:[
				{id:'bois_id', 					label:'BOIS ID',					width:'80',		postion:'left',		sortable:true},
				{id:'user_name',				label:'ユーザー名',					width:'100',	postion:'left',		sortable:true},
				{id:'person_name', 			label:'担当者名',						width:'100',	postion:'left',		sortable:true},
				{id:'mail', 						label:'メールアドレス',			width:'100',	postion:'left',		sortable:true},
				{id:'tel',							label:'電話番号',						width:'100',	postion:'left',		sortable:true},
				{id:'role',							label:'権限',							width:'50',		postion:'center',		sortable:true},
				{id:'mod_passwd_date',	label:'パスワード変更日',			width:'90',	postion:'left',		sortable:true},
				{id:'status',						label:'状態',							width:'50',		postion:'center',		sortable:true},
				{id:'last_login',				label:'最終ログイン日時',			width:'90',	postion:'left',		sortable:true},
				{id:'note',							label:'備考',							width:'150',	postion:'left',		sortable:true}
			]
			,
	initcondition:{
		search:['false']
	}
}


</div><%  "#main_list_body" %>
</div><%  "#main_list" %>

<div id="main_form" class="y_content" style="height:5px;">
<div id="main_form_body" class="r3form">
<div class="r3control_header">
var search2=new Rainy3Submenu(300, 200, searchForm2);
search2.setPreLoadAction(function(){
	rainy3.setButtonAction('button3');
	rainy3.setButtonAction('button4');
});
search2.setLoadAction(function(){
});

var header = {
  title:"子アカウント詳細",
  title_width:"150",
  controls:[
  		{id:'new', label:'新規作成', icon:'img/small_icon/new.png', disabledicon:'img/small_icon/new_disabled.png', click:function(){createUser()}, submenu:null, initdisable:false},
  		{id:'edit', label:'更新', icon:'img/small_icon/edit.png', disabledicon:'img/small_icon/edit_disabled.png', click:null, submenu:null, initdisable:true},
  		{id:'delete', label:'削除', icon:'img/small_icon/del.png', disabledicon:'img/small_icon/del_disabled.png', click:null, submenu:null, initdisable:true},
  		{id:'password', label:'パスワード発行', icon:'img/small_icon/passwd.png', disabledicon:'img/small_icon/passwd_disabled.png', click:null, submenu:null, initdisable:true},
  		{id:'floor', label:'フロア選択', icon:'img/small_icon/check.png', disabledicon:'img/small_icon/check_disabled.png', click:null, submenu:search2, initdisable:true}
  ]
}
</div>


var form = {
	url:'<%= children_form_path %>',
	label_width:'150',
	data_width:'300',
	example_width:'0',
	loadaction:function(){
		rainy3.getWindow('main_form').getHeader().getControl('edit').disable(false);
		rainy3.getWindow('main_form').getHeader().getControl('delete').disable(false);
		rainy3.getWindow('main_form').getHeader().getControl('password').disable(false);
		rainy3.getWindow('main_form').getHeader().getControl('floor').disable(false);
	},
	unloadaction:function(){
		rainy3.getWindow('main_form').getHeader().getControl('edit').disable(true);
		rainy3.getWindow('main_form').getHeader().getControl('delete').disable(true);
		rainy3.getWindow('main_form').getHeader().getControl('password').disable(true);
		rainy3.getWindow('main_form').getHeader().getControl('floor').disable(true);
	},
	forms:[
		{
			id:'bois_id',
			label:'BOIS ID',
			html:form1,
			example:'',
			plural:false
		},
		{
			id:'password',
			label:'パスワード',
			html:form2,
			example:'',
			plural:false
		},
		{
			id:'user_name',
			label:'ユーザー名',
			html:form3,
			example:'',
			plural:false
		},
		{
			id:'person_name',
			label:'担当者名',
			html:form4,
			example:'',
			plural:false
		},
		{
			id:'mail',
			label:'メールアドレス',
			html:form5,
			example:'',
			plural:false
		},
		{
			id:'tel',
			label:'電話番号',
			html:form6,
			example:'',
			plural:false
		},
		{
			id:'role',
			label:'権限',
			html:form7,
			example:'',
			plural:false
		},
		{
			id:'status',
			label:'状態',
			html:form8,
			example:'',
			plural:false
		},
		{
			id:'note',
			label:'備考',
			html:form9,
			example:'',
			plural:false
		}
	]
};

</div><%  "#main_form_body" %>
</div><%  "#main_form" %>





</div><%  "#main" %>



<div id="right_margin" class="x_content" style="width:5px;position:fixed;">
<div id="right_margin_height" class="y_content" style="height:10px;">
</div><%  "#right_margin_height" %>
</div><%  "#right_margin" %>

</div><% "// #contents" %>
<div class="contents_y_space"></div>
<div id="footer" class="frame_width">

<% "// overlayで背後にfocusが回らないようにする入力エリア" %>
<div class="tab_stop_box"><input type="text" name="tab_stop_2" class="tab_stop"></div>

</div><% "// #footer" %>

app/views/children/list.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<rainy3 type="response">
<head>
<result><%= @result %></result>
<title><%= @title %></title>
<message><%= @message %></message>
<forward>http://www.google.com</forward>
<data_type>grid</data_type>


<page_num>1</page_num>
<page_size>10</page_size>
<total_size>10</total_size>
</head>

<body>
<rows>

<% for i in @dummy %>
<row id="<%= i %>">
<bois_id>BBT</bois_id>
<user_name>株式会社ブロードバンドタワ</user_name>
<person_name>山田　太郎</person_name>
<mail>bbt@bbtower.co.jp</mail>
<tel>090-1111-2222</tel>
<role>親</role>
<mod_passwd_date>2013/12/31</mod_passwd_date>
<status>有効</status>
<last_login>2013/12/31</last_login>
<note>備考備考</note>
</row>
<% end %>

</rows>
</body>
</rainy3>