config/routes.rb
Bois::Application.routes.draw do

  
	match '' => 'top#index', :via => [:get], :as => :top_index
	match 'top' => 'top#index', :via => [:get]
	match 't:id' => 'top#topic', :via => [:get], :as => :top_topic

	match 'request' => 'request#index', :via => [:get,:post], :as => :request_index

	match 'power' => 'power#index', :via => [:get], :as => :power_index
	match 'power/list' => 'power#list', :via => [:post], :as => :power_list
	match 'power/graph' => 'power#graph', :via => [:get,:post], :as => :power_graph

	match 'children' => 'children#index', :via => [:get], :as => :children_index
	match 'children/list' => 'children#list', :via => [:post], :as => :children_list
	match 'children/form' => 'children#form', :via => [:post], :as => :children_form
	match 'children/create' => 'children#create', :via => [:post], :as => :children_create
	match 'children/edit' => 'children#edit', :via => [:post], :as => :children_edit
	match 'children/delete' => 'children#delete', :via => [:post], :as => :children_delete
	match 'children/passwd' => 'children#passwd', :via => [:post], :as => :children_passwd

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Bois - <%= yield :title %> - </title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Rainy3</title>
	<link rel="stylesheet" type="text/css" href="css/rainy3.css" />
	<link rel="stylesheet" type="text/css" href="css/user.menu.css" />
	<link rel="stylesheet" type="text/css" href="css/jquery.powertip.css" />
	<link rel="stylesheet" type="text/css" href="css/date.picker.css" />
	<link rel="stylesheet" type="text/css" href="css/time.picker.css" />
	<link rel="stylesheet" type="text/css" href="css/monthly.picker.css" />
	<link rel="stylesheet" type="text/css" href="css/hours.picker.css" />
	<link rel="stylesheet" type="text/css" href="css/rate.picker.css" />
	<link rel="stylesheet" type="text/css" href="css/bois.css" />

	<script type="text/javascript" src="/js/jquery-1.7.2.min.js" charset="utf-8"></script>
	<script type="text/javascript" src="/js/app.js" charset="utf-8"></script>
	<script type="text/javascript" src="/js/rainy3.js" charset="utf-8"></script>
	<script type="text/javascript" src="/js/user.menu.js"></script>
	<script type="text/javascript" src="/js/jquery.powertip.js"></script>
	<script type="text/javascript" src="/js/printf.js"></script>
	<script type="text/javascript" src="/js/date.picker.js"></script>
	<script type="text/javascript" src="/js/time.picker.js"></script>
	<script type="text/javascript" src="/js/monthly.picker.js"></script>
	<script type="text/javascript" src="/js/hours.picker.js"></script>
	<script type="text/javascript" src="/js/rate.picker.js"></script>
	<script type="text/javascript" src="/js/bois.js"></script>

	<%= yield :head %>


	<!--[if IE]>
	<script type="text/javascript">rainy3.ie=true;</script>
	<![endif]-->
	<script type="text/javascript">

<%
=begin
%>

	userMenu.logoutUrl='<%= do_logout_path %>';
	userMenu.accountUrl='<%= account_index_path %>';
	userMenu.passwordUrl='<%= password_index_path %>';
<%
=end
%>
	powerWindowUrl='<%= power_index_path %>';
	$(function(){
		// Release of screen protection 
		rainy3.releaseLoading();
		// Set Resize Event Function
		rainy3.setResizeFunction(function(){
			datePicker.hide();
			timePicker.hide();
			monthlyPicker.hide();
			hoursPicker.hide();
			ratePicker.hide();
	  });
		// Set Zoom
  });

  <%= yield :script %>

  </script>

</head>
<body> 

<%= yield %>

</body>
</html>